### ISSUE TITLE
Nyx space for astrodynamics?

### ISSUE THREAD

**Issue by ChristopherRabotin** [B612-Asteroid-Institute/astrodynamics#63]
Hi there,

I serendipitous found out about this repo. I have been developing the nyx astrodynamics toolkit for almost three years now. It's been validated against GMAT for orbit propagation and against JPL Monte the orbit determination.

I'd be happy to help you get started on using nyx. The code is available here (it's all in Rust): https://gitlab.com/chrisrabotin/nyx/ . Here is a draft of a tutorial: https://docs.rs/nyx-space/0.0.22/nyx_space/tutorial/index.html . 

Oh also, it's "freakishly" fast to quote someone who hopes to use it. It's about 6 to 8 times faster than GMAT for orbit propagation.

**Comment by carise** [comment]
Hi Chris, this sounds super interesting! Right now, we are using a mix of tools -- STK Components, find_orb, OpenOrb, Orekit. We are interested in how you are using Nyx, both for research as well as in Cloud. What's the best way to contact you?

**Comment by ChristopherRabotin** [comment]
It's currently used for simulations of the [CAPSTONE](https://www.nasa.gov/directorates/spacetech/small_spacecraft/capstone) mission, specifically for the Cislunar autonomous position system. I develop this on my own time, and the currently milestone (version 0.0.23) is focused on trajectory optimization using multiple shooting.

Let's chat by email: christopher.rabotin at gmail.com .

**Comment by carise** [comment]
B612 team met with Chris to talk about Nyx, and also started a separate discussion over email. I'm closing this issue, but if anyone thinks it should be reopened, we can reopen. :)
